### ISSUE TITLE
Return photos changing color on hover

### ISSUE THREAD

**Issue by whittede** [21ctownball/townball-website#34] opened 2024-03-17 17:51 UTC
In a previous commit of the site, the pictures on the homepage "popped" out with color when users hovered over them with the mouse. (I don't remember how this worked on mobile – was it any time a user scrolled past them?) People really liked this feature, but it was accidentally removed in a later release. We should add that functionality back.

**Comment by rschubkegel** [comment] 2024-03-18 15:13
Duplicate of #32

**Closed by rschubkegel** 2024-03-18 15:13 UTC
